# This file contains the information needed for Gulp to run.
#
# 1. Add all your file names, paths and settings here.
# 2. Run gulp for development mode and gulp --prod for production mode.

---

## Project syncing
browsersync:
  debug:  true
  notify: true
  open:   false
  port:   4000
  preferences:
    clicks: false
    scroll: false

## Project file deleting
clean:
  dest: 'dist'

## Image uploading
cloudinary:
  account:
    name: "mat-teague"
    key: "925148782699291"
    secret: "2pdj9N2gyIvWxOquVwb8jf8WyMo"
  dest: 'dist/assets/images'
  manifest: "config/cloudinary-manifest.json"
  src: 'src/assets/images/**/*.+(jpg|jpeg|png|svg|gif)'

### Copy files from tmp
copy:
  dest: 'dist/assets/'
  src: '.tmp/**/*'

### Fonts
fonts:
  dest: 'dist/assets/fonts'
  src: 'src/assets/fonts/*'

## Images
image:
  dest: 'dist/assets/images'
  icons: 'src/assets/images/icons/*.svg'
  src: 'src/assets/images/**/*.+(jpg|jpeg|png|svg|gif)'
  webp: 'src/assets/images/**/*.+(jpg|jpeg|png)'

## Jekyll
jekyll:
  debug: false
  silent: false
  incremental: true

## Project scripts
js:
  dest: 'dist/assets/js'
  src: 'src/assets/js/main.js'
  tmp: '.tmp/js'

## Project styles
sass:
  dest: 'dist/assets/css'
  src: 'src/assets/scss/main.scss'
  tmp: '.tmp/css'

### Vendor assets
vendors:
  dest: 'src/assets/vendors'

### Watch files
watch:
  fonts: 'src/assets/fonts/*'
  jekyll:
    - 'src/**/*.+(md|markdown)'
    - 'src/**/*.html'
    - 'src/**/*.+(yml|yaml)'
    - 'src/**/*.xml'
    - 'src/**/*.json'
    - 'src/**/*.txt'
  js: 'src/assets/js/**/*.js'
  images: 'src/assets/images/**/*'
  scss: 'src/assets/scss/**/*.scss'

